# CONFIGURATION OPTIONS


   # TOEVOEGEN?
# Require passkey on pairing
# CONFIG_ZMK_BLE_PASSKEY_ENTRY=y

   # Sleep timeout 30 minutes
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

   # Fix battery reporting on Windows
#CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

   # Report battery peripheral battery level
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y