name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
  
  dump-dts:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dump DTS kscan section
        run: |
          echo "=== Checking DTS output for kscan ==="
          find build -name "zephyr.dts" -exec grep -A25 "kscan" {} \; || echo "No kscan section found"
